modLoader="javafml"
loaderVersion="[38,)"
license="MIT License"
[[mods]]
modId="ea"
version="${file.jarVersion}"
displayName="Enameled Armor Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enameled-armor"
updateJSONURL="https://github.com/Lupicus/EnameledArmor/raw/master/update.json"	
logoFile="logo.png"
authors="MacTso, Lupicus"
description='''Enameled Armor Mod.'''
[[dependencies.ea]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
